### ISSUE TITLE
Small fix for Swift2.3

### ISSUE THREAD

**Issue by glancashire** [SimonFairbairn/SwiftyMarkdown#31]
First thanks for you work.

Please add a ! to the line 398
    finalFont = UIFont(descriptor: boldDescriptor!, size: styleSize)

**Comment by avalla** [comment]
if someone needs the swift2.3 version..

pod 'SwiftyMarkdown', :git => 'https://github.com/avalla/SwiftyMarkdown', :branch => 'swift2.3'

**Comment by glancashire** [comment]
Thanks

Graham

**Comment by DavidLari** [comment]
This is actually not the correct way to make this work. The API has changed to make the return from withSymbolicTraits optional. This means there are circumstances where you get nil back and crash when unwrapping. Rather than add the !, one should put in a 'if let' on the boldDescriptor, and likewise the italicDescriptor. If it fails, then you would just get regular text back, rather than crashing.

'''
            if let italicDescriptor = finalFontDescriptor.withSymbolicTraits([.traitItalic, .traitUIOptimized]) {
                finalFont = UIFont(descriptor: italicDescriptor, size: styleSize)
            }
'''
