### ISSUE TITLE
Font defaults to TimesNewRoman in iOS 13

### ISSUE THREAD

**Issue by verstaen** [SimonFairbairn/SwiftyMarkdown#64]
Starting with iOS 13, the system default font can't be accessed using fontName. This breaks the default font used on device.

More precisely, this code:

        let font = UIFont.systemFont(ofSize: 12.0)
        let newFont = UIFont(name: font.fontName, size: 12.0)
        print(newFont?.fontName)

prints the expected .SFUIText on Simulator and on device with iOS 12, but TimesNewRomanPSMT on device with iOS 13.

As a consequence, in attributedStringFromString(), when attempting to load the default font (stored through its name, .SFUIText), iOS 13 returns TimesNewRoman...

We could either special case .SFUIText (not my favorite, this will break if Apple modifies this name for any reason), or handle the "system default" font case. I'd be happy to work on a PR.

**Comment by ayoy** [comment]
I stumbled upon this issue while migrating to iOS 13, and prepared a workaround in my fork. It changes `FontProperties` API to take a ready-made `UIFont` object, instead of name and size. It's not thoroughly tested but it does the job for me.

Have a look at [this](https://github.com/DonkeyRepublic/SwiftyMarkdown/commit/11dc662c72d780136152907779104d336d8f7f87) commit if you like.

**Comment by verstaen** [comment]
Thanks @ayoy , this is very helpful. I worked around this by checking after instantiating UIFont if the resulting font name is the expected one, if not then use the system font and not a random one. I'll work on a PR. I believe both these fixes can be useful.
